services:
  db:
    image: postgres:15
    shm_size: 1g
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  api:
    depends_on:
      - db
    build: "."
    ports:
      - "8080:8080"
    command: [
      "oracle-fetch", "api",
      "--database-url", "postgres://postgres:postgres@postgres:5432/postgres",
      "--host", "localhost:8080",
    ]
  fetcher:
    depends_on:
      - db
    build: "."
    command: [
      "oracle-fetch", "fetch",
      "--database-url", "postgres://postgres:postgres@postgres:5432/postgres",
      "--eth-endpoint", "your-eth-endpoint",
    ]
