services:
  postgres:
    image: postgres:15
    shm_size: 1g
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  api:
    depends_on:
      - postgres
    build: "."
    ports:
      - "8080:8080"
    command: [
      "oracle-fetch", "api",
      "--database-url", "postgres://postgres:postgres@postgres:5432/postgres",
      "--host", ":8080",
    ]
    restart: always
  fetcher:
    depends_on:
      - postgres
    build: "."
    volumes:
      - "./config.json:/config.json"
    command: [
      "oracle-fetch", "fetch",
      "--database-url", "postgres://postgres:postgres@postgres:5432/postgres",
      "--config", "/config.json",
    ]
    restart: always
