definitions:
  api.AvgPriceResponse:
    properties:
      avg_price:
        example: 1234500000000.000000 (8 extra decimal places, so it means 12345)
        type: string
      first_price_timestamp:
        example: "2023-03-18T01:23:45Z"
        type: string
      last_price_timestamp:
        example: "2023-03-18T01:23:45Z"
        type: string
      price_count:
        example: 10
        type: integer
      token:
        example: BTC
        type: string
      unit:
        example: USD
        type: string
    type: object
  api.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  api.PriceResponse:
    properties:
      fetch_timestamp:
        example: "2023-03-18T01:23:45Z"
        type: string
      price:
        example: 1234500000000.000000 (8 extra decimal places, so it means 12345)
        type: string
      price_timestamp:
        example: "2023-03-18T01:23:45Z"
        type: string
      token:
        example: BTC
        type: string
      unit:
        example: USD
        type: string
    type: object
info:
  contact: {}
paths:
  /avg_price:
    get:
      description: Retrieves the average price of a token-unit pair over the given
        time range
      parameters:
      - description: The token part of the pair
        in: query
        name: token
        required: true
        type: string
      - description: 'The unit part of the pair (default: USD)'
        in: query
        name: unit
        type: string
      - description: The start of the time range to retrieve the average price for,
          in RFC3339 format (e.g. 2023-03-18T01:23:45+08:00)
        in: query
        name: from
        required: true
        type: string
      - description: The end of the time range to retrieve the average price for,
          in RFC3339 format (e.g. 2023-03-18T01:23:45+08:00)
        in: query
        name: to
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Returns the average price of the token
          schema:
            $ref: '#/definitions/api.AvgPriceResponse'
        "400":
          description: Returns an error if the request is invalid
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Get the average price of a token-unit pair over a time range
      tags:
      - price
  /price:
    get:
      description: Retrieves the most recent price of a token-unit pair in the specified
        unit before the given timestamp
      parameters:
      - description: The token part of the pair
        in: query
        name: token
        required: true
        type: string
      - description: 'The unit part of the pair (default: USD)'
        in: query
        name: unit
        type: string
      - description: 'The fetch timestamp to retrieve the price for, in RFC3339 format
          (e.g. 2023-03-18T01:23:45+08:00) (default: current time)'
        in: query
        name: timestamp
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Returns the price of the token
          schema:
            $ref: '#/definitions/api.PriceResponse'
        "400":
          description: Returns an error if the request is invalid
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "404":
          description: Returns 404 if the price info is not found at the given timestamp
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Get the price of a token-unit pair at a given timestamp
      tags:
      - price
swagger: "2.0"
